version: "3"
services:
  api:
    image: node:16
    working_dir: /usr/src/app/
    # environment:
    #   - PUBLIC_URL=/trial-monitor
    volumes:
      - ./packages/server:/usr/src/app/
      - ./config:/usr/config
    command: /bin/sh -c 'chmod +x /usr/src/app/dev-start.sh && /usr/src/app/dev-start.sh'
    ports:
      - 3001:3001
  frontend:
    image: node:16
    working_dir: /usr/src/app/
    # environment:
    #   - PUBLIC_URL=/trial-monitor
      # - AUTH=KEYCLOAK
    volumes:
      - ./packages/client:/usr/src/app/
      - ./config:/usr/config
    command: /bin/sh -c 'chmod +x /usr/src/app/dev-start.sh && /usr/src/app/dev-start.sh'
    ports:
      - 3000:3000
  nginx_proxy:
    image: nginx:alpine
    environment:
      - PUBLIC_URL=/
    ports:
      - "80:80"
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf.template
    links:
      - api:api
      - frontend:frontend